// Auto-generated by the postman-to-k6 converter

import './libs/shim/core.js';
import './libs/shim/urijs.js';
import URI from './libs/urijs.js';
import { group } from 'k6';

export let options = { 
    maxRedirects: 4, 
    duration: '1m',
    vus: 100
  };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name:
      "https://chat.googleapis.com/v1/spaces/AAAAop7Pmho/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Vgg5rVDxwsscAuXAS0sA5pI-c__2tLI-bA8NwNQ1-PU",
    id: "918a7a83-399a-44b7-b95b-81422b346200",
    method: "POST",
    address:
      "https://chat.googleapis.com/v1/spaces/AAAAop7Pmho/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Vgg5rVDxwsscAuXAS0sA5pI-c__2tLI-bA8NwNQ1-PU",
    data:
      '{\n  "cards": [\n    {\n      "header": {\n        "title": "Automation Test Report - Jurnal"\n      },\n      "sections": [\n        {\n          "widgets": [\n            {\n              "textParagraph": {\n                "text": "\\ud83e\\udd16 Summarize execution report of \\ud83d\\udcb0 <u><b>Jurnal.id</b></u> - icebox test for https://staging.cd.jurnal.id and https://my.jurnal.id\\n \\ud83d\\udcca Test results: <br> \\u2705 : A Report Balance Sheet [3 / 3] (177.1s)\\n \\u2705 : A Report Balance Sheet [3 / 3] (177.1s)\\n \\u2705 : A Report Balance Sheet [3 / 3] (177.1s)\\n Total Scenarios: 3 Total Passed: 3 (100.0%)\\nVisit <a href=\\"https://jenkins.mekari.io/job/SDET-JURNAL/job/sdet_icebox_pr/1301/\\">Jenkins PullRequest pr sdet-icebox #1301</a> to view detail"\n              }\n            }\n          ]\n        }\n      ]\n    }\n  ]\n}',
    headers: {
      "Content-Type": "application/json"
    }
  });

  postman[Request]({
    name:
      "https://chat.googleapis.com/v1/spaces/AAAAop7Pmho/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Vgg5rVDxwsscAuXAS0sA5pI-c__2tLI-bA8NwNQ1-PU Copy",
    id: "197f0ba7-8d5a-4290-bf91-ace6b4aedb2b",
    method: "POST",
    address:
      "https://chat.googleapis.com/v1/spaces/AAAAop7Pmho/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Vgg5rVDxwsscAuXAS0sA5pI-c__2tLI-bA8NwNQ1-PU",
    data:
      '{\n  "cards": [\n    {\n      "header": {\n        "title": "Automation Test Report - Jurnal"\n      },\n      "sections": [\n        {\n          "widgets": [\n            {\n              "textParagraph": {\n                "text": "\\ud83e\\udd16 Summarize execution report of \\ud83d\\udcb0 <u><b>Jurnal.id</b></u> - icebox test for https://staging.cd.jurnal.id and https://my.jurnal.id\\n \\ud83d\\udcca Test results: <br> \\u2705 : A Report Balance Sheet [3 / 3] (177.1s)\\n \\u2705 : A Report Balance Sheet [3 / 3] (177.1s)\\n \\u2705 : A Report Balance Sheet [3 / 3] (177.1s)\\n Total Scenarios: 3 Total Passed: 3 (100.0%)\\nVisit <a href=\\"https://jenkins.mekari.io/job/SDET-JURNAL/job/sdet_icebox_pr/1301/\\">Jenkins PullRequest pr sdet-icebox #1301</a> to view detail"\n              }\n            }\n          ]\n        }\n      ]\n    }\n  ]\n}',
    headers: {
      "Content-Type": "application/json"
    }
  });

  postman[Request]({
    name:
      "https://chat.googleapis.com/v1/spaces/AAAAop7Pmho/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Vgg5rVDxwsscAuXAS0sA5pI-c__2tLI-bA8NwNQ1-PU Copy",
    id: "8ceaa369-0adf-4998-a1b3-99788be3fe98",
    method: "POST",
    address:
      "https://chat.googleapis.com/v1/spaces/AAAAop7Pmho/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Vgg5rVDxwsscAuXAS0sA5pI-c__2tLI-bA8NwNQ1-PU",
    data:
      '{\n  "cards": [\n    {\n      "header": {\n        "title": "Automation Test Report - Jurnal"\n      },\n      "sections": [\n        {\n          "widgets": [\n            {\n              "textParagraph": {\n                "text": "\\ud83e\\udd16 Summarize execution report of \\ud83d\\udcb0 <u><b>Jurnal.id</b></u> - icebox test for https://staging.cd.jurnal.id and https://my.jurnal.id\\n \\ud83d\\udcca Test results: <br> \\u2705 : A Report Balance Sheet [3 / 3] (177.1s)\\n \\u2705 : A Report Balance Sheet [3 / 3] (177.1s)\\n \\u2705 : A Report Balance Sheet [3 / 3] (177.1s)\\n Total Scenarios: 3 Total Passed: 3 (100.0%)\\nVisit <a href=\\"https://jenkins.mekari.io/job/SDET-JURNAL/job/sdet_icebox_pr/1301/\\">Jenkins PullRequest pr sdet-icebox #1301</a> to view detail"\n              }\n            }\n          ]\n        }\n      ]\n    }\n  ]\n}',
    headers: {
      "Content-Type": "application/json"
    }
  });
}
